### ISSUE TITLE
Jax library, module not found error using anaconda-navigator

### ISSUE THREAD

**Issue by krishna-kumar-netizen** [Shubodh/MR-project1-pgo#1]
I have successfully installed Jax library in my conda environment. But when when I try to use it on jupyter notebook(Opened in the same environment) . I get **_ModueNotFoundError for Jax._**,  **I am using Python version  3.7** 
. And  **Jupyter notebook version 6.1.1**

![Screenshot from 2020-10-05 19-54-15](https://user-images.githubusercontent.com/55920542/95091952-b32a5a80-0744-11eb-874b-b32d4b163e9f.png)

![Screenshot from 2020-10-05 19-56-18](https://user-images.githubusercontent.com/55920542/95092170-f84e8c80-0744-11eb-90a4-4bf06584dae9.png)

Can you please help me Sir.

**Comment by Shubodh** [comment]
@krishna-kumar-netizen Can you try the following:

- Do a pip freeze and conda export to see if the package is actually installed in that particular environment.
- Run `which python` and check if you are actually using the conda python.

Let me know what you find out.

**Comment by krishna-kumar-netizen** [comment]
Sir. as you instructed I created new environment. and installed and did pip freeze. pip freeze showed me jax library after installation. And python is also installed . I am using python 3.7. 

And yet the face the same error of ModuleNotFound. I doing the project on google colab. Hope I won't face any issues. (Can I do it?)

**Comment by krishna-kumar-netizen** [comment]
Sir, can I do it on google colab?

**Comment by Shubodh** [comment]
You can do it on Colab but it could be a bit of hassle (for example for using GUI based tools like g2o_viewer/EVO, you will have to download the data files to your local system and inspect them). But it's doable. However, we should be able to fix this problem without looking for workarounds:

When you do `pip install`, you can see above that it is getting installed in `-/anaconda3/envs/mr_assígnment1/lib/python3.7/site-packages`. Now run the following commands:

```
which python
python -c "import sys; print(sys.path)"
```

Paste the output in your reply. If from the above outputs, if you do not see `../lib/../site-packages`, then import won't work.
Then you'll have to explicitly set your $PYTHONPATH variable pointing to that path. Then it will be able to import from next time. You can set PYTHONPATH to that path as follows:
 ```
export PYTHONPATH="your-path-here"
echo $PYTHONPATH #check if you set it correctly
```

Let me know if it works.

**Comment by krishna-kumar-netizen** [comment]
Sir I have done as instructed, and I am able to see the correct path. After I ran the commands that you mentioned. And yet I am facing the same error while importing i.e. ModuleNotFoundError. Attached is the image. 

![Screenshot from 2020-10-08 21-56-21](https://user-images.githubusercontent.com/55920542/95487624-30a6d280-09b2-11eb-8df4-29cc091d4920.png)

**Comment by Shubodh** [comment]
Let us continue this discussion on email. Can you please drop an email to `p.saishubodh@gmail.com`?

**Comment by SanjayPapaiahgari25** [comment]
Check may be whether you are running the right kernel when you open jupyter or whether the file is running on python3 kernel,because atleast in my case,when i run jupyter lab,my file is opened using python3 kernel instead of mr_assignment1 kernel.May be that could also be the issue.

**Comment by Shubodh** [comment]
Resolved this issue personally.

The issue was he was using anaconda-navigator and there's some problem with the way it imports packages when jupyter notebook is installed. The way to resolve it is to keep things simple and use the bare bones `jupyter notebook` (just launch `jupyter notebook` from terminal) and it works perfectly fine.
