### ISSUE TITLE
Setting up g2o : cmake warnings & optional requirements installation

### ISSUE THREAD

**Issue by gems047** [Shubodh/MR-project1-pgo#2]
Clone the g2o repository, then cd into it , getting below error at cmake ../

mkdir build
cd build
cmake ../

error :
==============
-- Compiling on Unix
-- Could NOT find CHOLMOD (missing: CHOLMOD_INCLUDE_DIR CHOLMOD_LIBRARIES) 
-- Could NOT find CSPARSE (missing: CSPARSE_INCLUDE_DIR CSPARSE_LIBRARY) 
-- Compiling with OpenGL support
CMake Warning at cmake_modules/FindQGLViewer.cmake:1 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:175 (find_package)

Qt5 not found. Install it and set Qt5_DIR accordingly
-- Could NOT find QGLVIEWER (missing: QGLVIEWER_INCLUDE_DIR QGLVIEWER_LIBRARY) 
-- Compiling g2o apps
-- Compiling g2o examples
-- Compiling with GCC
-- Eigen3 version 3.2.92 fou

**Comment by Shubodh** [comment]
@gems047 Firstly, please paste the complete output, it looks like you didn't copy the ending properly.

This is not an error but just a warning telling you you have not installed the ["optional requirements"](https://github.com/RainerKuemmerle/g2o#optional-requirements). Going ahead with building it would just work fine.

But wait, I missed a point when I said these requirements are not necessary for the scope of this project in the helper notebook. These "optional requirements" are actually necessary for your project. 

Please look at that [page](https://github.com/RainerKuemmerle/g2o#optional-requirements) and install them one by one: You can install them using `sudo apt-get install package_name`, for example `sudo apt-get install libsuitesparse-dev`. 

If you have already built g2o, you can just delete the `build` folder and re-do it again after installing all the optional requirements.

**Comment by gems047** [comment]
Here is the ending(continued from previous post):

-- Eigen3 version 3.2.92 found in /usr/include/eigen3, but at least version 3.3 is required
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Courses/g2o/build

**Comment by Shubodh** [comment]
Okay, closing this issue as this is not actually an error.
