### ISSUE TITLE
Not able to install eigen version 3.3

### ISSUE THREAD

**Issue by sagrikanagar** [Shubodh/MR-project1-pgo#3]
I'm getting this error while trying to set up g2o:

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Eigen3 (missing: EIGEN3_VERSION_OK) (Required is at least
  version "3.3")

I'm not able to figure out how to install version 3.3

**Comment by Shubodh** [comment]
Can you try `sudo apt-get install libeigen3-dev=3.3.4-4` and run cmake again?

**Comment by sagrikanagar** [comment]
Didn't work, that version is not available on Ubuntu 16.04. However, version 3.3~beta1-2 is available which is what I'm downloading. It still gives this error.

**Comment by Shubodh** [comment]
Okay, for Ubuntu 16.04, stable versions of Eigen 3.3 doesn't seem to be available via `apt-get`. No worries, we can setup Eigen in the following way:
(See [official website](http://eigen.tuxfamily.org/dox/GettingStarted.html) for more details)

Firstly, remove your older versions. If you installed via `apt-get`, they will be installed in `/usr/include/eigen3`. If unable to find there, run `sudo locate eigen3` to find out where they reside. 

Download the compressed source code from the above website. I'll walk you through an example: Say you want to setup 3.3.4 version, then [download this](https://gitlab.com/libeigen/eigen/-/archive/3.3.4/eigen-3.3.4.zip). Unzip it. Now, Eigen is a header-only library, there is no need to install anything. Just copy your unzipped folder (by the name `eigen-3.3.4`) to `/usr/local/include/` (or perhaps even `/usr/include/`). Then cmake should be able to find the Eigen library with correct version.

Let me know if it doesn't work.

**Comment by sagrikanagar** [comment]
It worked. Thanks a lot.

**Comment by Shubodh** [comment]
Great!
