### ISSUE TITLE
g2o installation

### ISSUE THREAD

**Issue by gems047** [Shubodh/MR-project1-pgo#4]
Tried to install g2o on Ubuntu 18.04 . cmake seems to run fine but invoking g2o_viewer from linux terminal says :

g2o_viewer: command not found

Also eigen3 version is 3.3.4
( using this command pkg-config --modversion eigen3)

Please suggest how to test if g2o is installed correctly

Below is cmake ../ logs

 cmake ../
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling on Unix
-- Found CHOLMOD: /usr/include/suitesparse  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Found CHOLMOD and its dependencies
-- Found CSPARSE: /usr/include/suitesparse  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Compiling with OpenGL support
-- Found QGLVIEWER: /usr/include/QGLViewer  
-- Compiling g2o apps
-- Compiling g2o examples
-- Compiling with GCC
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3") 
-- Generating position indpendent code for slam2d because Qt5 was built with -reduce-relocations
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Courses/Mobile_Robotics/Project1/g2o/build

**Comment by Shubodh** [comment]
Have you added what I mentioned in the helper notebook to the `.bashrc`
file?

**Comment by gems047** [comment]
Below is last line in '.bashrc'  :

export PATH=$PATH:/home/user/Courses/Mobile_Robotics/Project1/g2o/bin/

**Comment by jeetv** [comment]
i am also getting same issue:
"g2o_viewer: command not found"

**Comment by Shubodh** [comment]
Okay, please do the following things and paste your output:

- `cd` to `/home/user/Courses/Mobile_Robotics/Project1/g2o/bin/` and do an `ls` and share your output
- If you find `g2o_viewer` there, navigate to that directory and do `./g2o_viewer path_to_your_g2o_file`. If that works, then I will let you know how you can run from anywhere.

**Comment by jeetv** [comment]
![image](https://user-images.githubusercontent.com/29459233/95674260-953d7980-0bcc-11eb-91ac-3c8ddba4898f.png)

**Comment by Shubodh** [comment]
@jeetv I have made an announcement on Moodle previously about "Optional Requirements". Please take a look [at this](https://www.notion.so/saishubodh/Project-1-Pose-Graph-Optimization-scratch-g2o-5e282c09de174e2989e2dd6178bd8d31#2325d070e51f46fc850c54d9016da079). You'll have to do `cmake` and build `g2o` again. Don't worry, it is just a set of `apt-get install` commands and then delete the old `build` folder and just repeat the build process which you've already successfully done.

**Comment by Shubodh** [comment]
@gems047 Your issue might be the same too. Please take a look and let me know if it doesn't answer your question.

**Comment by jeetv** [comment]
@Shubodh Thank you very much, these steps worked for me, now I am able access g2o_viewer command

**Comment by Shubodh** [comment]
Great, will close the issue after @gems047 confirms these steps worked for you as well.

**Comment by gems047** [comment]
g2o_viewer is working from linux terminal now .  But g2o_viewer is not recognized from jupyter notebook. Is that fine

In case we want to uninstall g2o later what steps we need to follow

**Comment by Shubodh** [comment]
You need to use terminal itself. Not necessary to run from notebook. 

Just delete the build folder and remove the line from `.bashrc` file. 

Closing issue.
