### ISSUE TITLE
Error while installing g2o in ceres/jet.h

### ISSUE THREAD

**Issue by sampath-inguva** [Shubodh/MR-project1-pgo#6]
Sir, I have followed the following steps
1. Cloned the g2o repository
2. Installed the following libraries(libsuitesparse-dev, qtdeclarative5-dev, qt5-qmake, libqglviewer-dev-qt5, cmake ,libeigen3-dev)
Inside the g2o repository created a new folder build inside g2o, then did cmake ../(It also ran properly)
When given the command make, it ran successfully till 90% then showed up an error which I couldn't figure out(Attaching the image below). Kindly look into it.(I am an ubuntu 16.04 user)
![WhatsApp Image 2020-10-11 at 22 51 04](https://user-images.githubusercontent.com/68137590/95991338-46047c80-0e4a-11eb-8f82-22114b46fd2f.jpeg)

**Comment by Shubodh** [comment]
Hi, 
It looks like it is a problem with Eigen version.
Given that you are using 16.04, how did you install Eigen? Look at the issue [here](https://github.com/Shubodh/MR-project1-pgo/issues/3#issuecomment-706130840), `apt-get` will not install the correct version. Follow that comment for detailed instructions on how to setup correct Eigen version..

**Comment by sampath-inguva** [comment]
Sir thanks a lot it worked for me I did complete make now :)
