### ISSUE TITLE
cannot cmopile the jax showing the erorr

### ISSUE THREAD

**Issue by mohitpavan123** [Shubodh/MR-project1-pgo#8]
![image](https://user-images.githubusercontent.com/60888617/96412603-02be5b00-1208-11eb-95e1-a8c54ac7f05a.png)

oduleNotFoundError                       Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/scipy/__init__.py in <module>
    128     try:
--> 129         from scipy.__config__ import show as show_config
    130     except ImportError:

ModuleNotFoundError: No module named 'scipy.__config__'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-c467f8f44af0> in <module>
----> 1 import jax.numpy as jnp
      2 """
      3 Basically, use "jnp" instead of using "np", our favourite numpy library.
      4 All functions work as it is (at least that are required for this project).
      5 Be careful though:

~/anaconda3/lib/python3.8/site-packages/jax/__init__.py in <module>
     20 # flake8: noqa: F401
     21 from .config import config
---> 22 from .api import (
     23   ad,  # TODO(phawkins): update users to avoid this.
     24   argnums_partial,  # TODO(phawkins): update Haiku to not use this.

~/anaconda3/lib/python3.8/site-packages/jax/api.py in <module>
     35 from contextlib import contextmanager, ExitStack
     36 
---> 37 from . import core
     38 from . import lib
     39 from . import linear_util as lu

~/anaconda3/lib/python3.8/site-packages/jax/core.py in <module>
     29 import numpy as np
     30 
---> 31 from . import dtypes
     32 from .config import FLAGS, config
     33 from . import linear_util as lu

~/anaconda3/lib/python3.8/site-packages/jax/dtypes.py in <module>
     29 from . import util
     30 from .config import flags
---> 31 from .lib import xla_client
     32 
     33 FLAGS = flags.FLAGS

~/anaconda3/lib/python3.8/site-packages/jax/lib/__init__.py in <module>
     52 
     53 from jaxlib import xla_client
---> 54 from jaxlib import lapack
     55 if version <  (0, 1, 53):
     56   from jaxlib import pytree  # pytype: disable=import-error

jaxlib/lapack.pyx in init lapack()

~/anaconda3/lib/python3.8/site-packages/scipy/__init__.py in <module>
    132         being in scipy source directory; please exit the SciPy source
    133         tree first and relaunch your Python interpreter."""
--> 134         raise ImportError(msg)
    135 
    136     from scipy.version import version as __version__

ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.

showing these errors please help @Shubodh

**Comment by Shubodh** [comment]
let us have a call at 4 pm, reach me on email. (we can finalize time on email) @mohitpavan123

**Comment by Shubodh** [comment]
uninstalling scipy and reinstalling it worked.
